### ISSUE TITLE
Old render state stays while preparing new one and OGG warning when exporting WAV

### ISSUE THREAD

**Issue by linuxgemini** [KaleidonKep99/Keppys-MIDI-Converter#1]
![screenshot_120](https://cloud.githubusercontent.com/assets/4682655/12020930/09ad4ed6-ad8a-11e5-9866-d40096228ad2.png)
This is the preparing state. But it shows it is aborted.

![screenshot_121](https://cloud.githubusercontent.com/assets/4682655/12020929/09ab3a60-ad8a-11e5-9115-0ddb2647a349.png)
Warning about OGG size while rendering WAV.

**Comment by KaleidonKep99** [comment]
Both fixed in [release 8.8.5] (https://github.com/KaleidonKep99/Keppys-MIDI-Converter/releases/tag/8.8.5).
