### ISSUE TITLE
Soundfont list not saving

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/Keppys-MIDI-Converter#10]
The converter needs a soundfont list keeper, just like Keppy's Driver. The soundfont list clears itself when you quit the converter (then run the converter), resulting as a bug.

**Comment by KaleidonKep99** [comment]
This is not an issue, I made KMC act like this to allow people to change the soundfont list for every session they run. Lol.

**Comment by KaleidonKep99** [comment]
+ That's a stupid idea tbh.

**Comment by DevanWolf** [comment]
At least can you just add the option to enable or disable saving/clearing the soundfont list on exit?
