### ISSUE TITLE
UI Glitch

### ISSUE THREAD

**Issue by Blue-Guy** [KaleidonKep99/Keppys-MIDI-Converter#11]
![image](https://cloud.githubusercontent.com/assets/16492168/17644249/6bacf5d6-614f-11e6-8534-8e1d4fdf1437.png)

**Comment by KaleidonKep99** [comment]
I'll fix that on version 12.2.3.

**Comment by KaleidonKep99** [comment]
Fixed, [download it here.] (https://github.com/KaleidonKep99/Keppys-MIDI-Converter/releases/tag/12.2.3)
