### ISSUE TITLE
Small funny glitch

### ISSUE THREAD

**Issue by Theblackmidi72** [KaleidonKep99/Keppys-MIDI-Converter#13]
![pauseglitch](https://cloud.githubusercontent.com/assets/21037985/17853544/47f7d65c-6897-11e6-9b0b-6a425ece51db.PNG)
Lol

**Comment by KaleidonKep99** [comment]
Holy moly, I fix something and another problem appears... Lol.
I'll fix that now.

**Comment by KaleidonKep99** [comment]
Fixed as of version 13.0.4.
https://github.com/KaleidonKep99/Keppys-MIDI-Converter/releases/tag/13.0.4
