### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by Theblackmidi72** [KaleidonKep99/Keppys-MIDI-Converter#14]
![won twork](https://cloud.githubusercontent.com/assets/21037985/17890618/5e6c5492-6961-11e6-84eb-7892bc2ac38f.PNG)
It won't run

**Comment by KaleidonKep99** [comment]
In the Start menu.
![Picture](http://image.prntscr.com/image/a50fc6f350154c6498b71413b44e226a.png)

**Comment by Theblackmidi72** [comment]
Still error

**Comment by KaleidonKep99** [comment]
The issue has been probably caused by outdated language files in the installation directory.

Try this release: https://github.com/KaleidonKep99/Keppys-MIDI-Converter/releases/tag/13.0.7

**Comment by Theblackmidi72** [comment]
Solved!
