### ISSUE TITLE
Portable executable crashes on startup.

### ISSUE THREAD

**Issue by thegreatestminer** [KaleidonKep99/Keppys-MIDI-Converter#15]
Every time I run the portable version of Keppy's MIDI Converter, it crashes giving the error:
==== Start of Keppy's MIDI Converter Error ====
Object reference not set to an instance of an object.
====  End of Keppy's MIDI Converter Error  ====

This error **ONLY** happens on the portable version. The non-portable version works just fine.

(This has happened on both of my computers.)

**Comment by thegreatestminer** [comment]
![error](https://cloud.githubusercontent.com/assets/19188146/18039030/e9970738-6d6c-11e6-900f-c223e05796b8.PNG)
added error.png

**Comment by KaleidonKep99** [comment]
Fixed on version 13.1.6.
