### ISSUE TITLE
Add options to disable certain MIDI features (SysEx, portamento, instrument change, pitch bend, etc.)

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/Keppys-MIDI-Converter#17]
Disabling those features like SysEx would be good for GM only soundfonts like Scratch. Disable instrument change will also be good for piano only soundfonts.

**Comment by KaleidonKep99** [comment]
This is a MIDI converter, not a ;ODO driver. SysEx has no effect on it.
And you can change the instruments through an external MIDI editor.

**Comment by DevanWolf** [comment]
Can't you just do this on Keppy's Synthesizer?

**Comment by KaleidonKep99** [comment]
Can't you just ask this on the Keppy's Synthesizer's page? Lol.
