### ISSUE TITLE
Converter crashes after converting midis

### ISSUE THREAD

**Issue by thegreatestminer** [KaleidonKep99/Keppys-MIDI-Converter#18]
Well, I was converting 350 midis (just regular midis) to OGG format, but after 29-31 midis, the converter gives a Windows crash screen, so I was not able to get an error log.

Seems to crash when initializing the renderer.
This is the first time it has crashed for me during the rendering process.

Is this because of the sheer amount of midis queued, or is it something else? 

Running Windows 8.1 x86
2 GB RAM
Intel(R) Core(TM)2 Duo CPU E4600  @ 2.40GHz

![picture of the list of midis](https://puu.sh/rBgCk/9e8cf32605.png)

**Comment by KaleidonKep99** [comment]
The issue seems related to this one by DevanWolf. ((Issue 8: Keppy's MIDI Converter randomly crashes while converting on 32-bit Windows) [https://github.com/KaleidonKep99/Keppys-MIDI-Converter/issues/8])

I'll take a look at it with VMware.

**Comment by KaleidonKep99** [comment]
Fixed as of [14.0.6] (https://github.com/KaleidonKep99/Keppys-MIDI-Converter/issues/18)! Have fun with bulk-conversions! 😄

**Comment by DevanWolf** [comment]
Same problem on my machine.

**Comment by KaleidonKep99** [comment]
Re-fixed as of version [15.2.1](https://github.com/KaleidonKep99/Keppys-MIDI-Converter/releases/tag/15.2.1).

**Comment by DevanWolf** [comment]
The fix didn't work again.

**Comment by KaleidonKep99** [comment]
It's working on KMC 17.0.7.
