### ISSUE TITLE
Cancelling preview gives out error

### ISSUE THREAD

**Issue by thegreatestminer** [KaleidonKep99/Keppys-MIDI-Converter#19]
Welp, the new update spawned this error,

==== Start of Keppy's MIDI Converter Error ====
System.OverflowException: Arithmetic operation resulted in an overflow.
   at KeppyMIDIConverter.MainWindow.RealTimePlayBackBeta_DoWork(Object sender, DoWorkEventArgs e)
====  End of Keppy's MIDI Converter Error  ====

This happens when I am previewing a MIDI and the I cancel the playback. Happens sometimes, but gets annoying after time.
Luckily this doesn't crash the renderer, just it gives this error.

![http://i.imgur.com/yD2F1eY.png](19)

EDIT1: I think the 350 midis broke it and caused this error. 😆
EDIT2: This only happened after loading the 350 midis and then previewing one, and it should give out an error. If not, try previewing and cancelling multiple times until it pops up.

**Comment by KaleidonKep99** [comment]
**"Fixed""*! [Here] (https://github.com/KaleidonKep99/Keppys-MIDI-Converter/releases/tag/14.0.7).
