### ISSUE TITLE
Add support for Windows XP SP1

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/Keppys-MIDI-Converter#2]
When trying to run Keppy's MIDI Converter on Windows XP SP1, I keep getting an error saying "Only works on Windows XP SP2 or later". It would be nice if we could get it to work on Windows XP SP1 and convert MIDI files as it would!

**Comment by KaleidonKep99** [comment]
Are you sure you're not using an old version of the converter?
I restored the support for XP since version 8.7.6.

Closed.

**Comment by KaleidonKep99** [comment]
Ops I accidentally closed it.

**Comment by KaleidonKep99** [comment]
So?
In my tests, it works just fine on my Pentium 3 with Windows XP SP3.

**Comment by KaleidonKep99** [comment]
I'm sorry, but .NET 4.0 requires SP2 or newer.
