### ISSUE TITLE
MP3 rendering implementation

### ISSUE THREAD

**Issue by thegreatestminer** [KaleidonKep99/Keppys-MIDI-Converter#21]
**--SUGGESTION--**

Just curious,

Will you ever implement MP3 rendering? (using LAME)
Other than that, your software is great!

**Comment by KaleidonKep99** [comment]
Probably not.

First problem, MP3 is subsceptible to clipping (KMC supports VSTs now, so you can actually limit the audio).
Second, it's not an open-source format, while OGG is.
Third, audio-wise, OGG is far better than MP3, even at low bitrates.

So, here's the answer. lel

**Comment by thegreatestminer** [comment]
thanks :D

**Comment by KaleidonKep99** [comment]
I thinked about adding MP3 support for a bit, and I found out that LAME is actually open-source.

So here it is, [KMC 14.1.1 with MP3 support.] (https://github.com/KaleidonKep99/Keppys-MIDI-Converter/releases/tag/14.1.1)

**Comment by KaleidonKep99** [comment]
Oops I opened the issue back.
