### ISSUE TITLE
.MUS support

### ISSUE THREAD

**Issue by thegreatestminer** [KaleidonKep99/Keppys-MIDI-Converter#22]
**suggestion and question**

Hi Keppy, love your software!

I was wondering if you could add some type of support for *.MUS files. (They're like MIDIs, but used in old iD Software games.) There's only one utility for MUS files, but its quite buggy and doesn't work that much. (mus2midi)

If that were to be possible that would great! (if not, its OK :D)

**Comment by KaleidonKep99** [comment]
MIDI support is handled by BASSMIDI itself, not by the converter.
The converter is just a "GUI" that interfaces with the BASS libraries.

I suggest you to make a post about this at the Un4seen Forum, [which you can find here](http://www.un4seen.com/forum/).

**Comment by thegreatestminer** [comment]
Ah, makes sense. Thanks anyways!
