### ISSUE TITLE
Latest converter always stuck on top

### ISSUE THREAD

**Issue by thegreatestminer** [KaleidonKep99/Keppys-MIDI-Converter#26]
Basically any other windows the converter makes (excluding the save window) is behind the converter itself, making it basically impossible to access them. Some windows are able to be Alt+Space'd and moved from there.

https://youtu.be/cbT70tJ0I4k

**Comment by KaleidonKep99** [comment]
https://www.youtube.com/watch?v=Xuyjw2JuzYg&feature=youtu.be

I don't have such issue.

**Comment by thegreatestminer** [comment]
Hmmm, not sure. I might try re-installing.

**Comment by thegreatestminer** [comment]
Huh, just reinstalled and now it doesn't occur. May have been some weird rare bug.

I guess this can be closed now.
