### ISSUE TITLE
Notes and Length still display N/A with really big MIDIs

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/Keppys-MIDI-Converter#27]
![untitled](https://cloud.githubusercontent.com/assets/15729831/25579494/a66d954c-2ea2-11e7-9a90-3a4410dab539.png)

**Comment by KaleidonKep99** [comment]
You have to hold CTRL when clicking "Open" in the file dialog.

**Comment by KaleidonKep99** [comment]
![image](https://cloud.githubusercontent.com/assets/11065274/25584105/fb769eac-2e94-11e7-9d62-42b060f61fde.png)
Here's a 170MB MIDI.

**Comment by KaleidonKep99** [comment]
Since this is not an issue, I'll just close it. Lel.

Also, you now have to hold CTRL while opening the MIDI import dialog.
