### ISSUE TITLE
Suggestion: Add KS feature "Ignore note between two velocity values"

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/Keppys-MIDI-Converter#28]
Can you add this feature of KS to KMC? (Just to make it go passes crash parts easier)

**Comment by KaleidonKep99** [comment]
It actually slows down MIDI playback, since it'll keep notes playing for more time.

**Comment by KaleidonKep99** [comment]
**DERP** I actually misread the title.

BTW, no I can't, since all the events are handled by BASSMIDI itself, unlike Keppy's Synthesizer, where I can edit the events myself before passing them to it. :(

Sorry fam, closed.
