### ISSUE TITLE
Latest version of installer is not compatible with Windows 10 32-bit

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/Keppys-MIDI-Converter#29]
The installer from the updater says: This program does not support the version of Windows your computer is running.
Which is not compatible with 32-bit Windows. The installer from GitHub releases work fine.

**Comment by KaleidonKep99** [comment]
The installer from the updater is the same as the installer from GitHub.
The update tool probably has an unstable connection, which can be caused by bad ADSL signal and packet loss.
