### ISSUE TITLE
When Rendering TH3 Parts, It crashed

### ISSUE THREAD

**Issue by KnockPlayz** [KaleidonKep99/Keppys-MIDI-Converter#31]
Here's the screenshot.
![image](https://user-images.githubusercontent.com/22779352/29338412-1322a888-81e3-11e7-8aa0-70205a7abb01.png)

**Comment by KaleidonKep99** [comment]
Fixed as of [version 17.2.0](https://github.com/KaleidonKep99/Keppys-MIDI-Converter/releases/tag/17.2.0).
You should explain better next time, I had to talk with you about it on Discord.

Closed.
