### ISSUE TITLE
Loudmax doesn't work and the window gets smaller each time I convert a midi.

### ISSUE THREAD

**Issue by AwesomeGamer89** [KaleidonKep99/Keppys-MIDI-Converter#33]
https://i.imgur.com/TwwH22u.png

**Comment by KaleidonKep99** [comment]
It looks like you're not using Windows 10's native DPI scaling, but rather a custom value.
![image](https://user-images.githubusercontent.com/11065274/31860567-3cdcfaf2-b71c-11e7-94d1-16c0e5976ff7.png)
It works on my end.

I'll fix LoudMax.

**Comment by KaleidonKep99** [comment]
https://github.com/KaleidonKep99/Keppys-MIDI-Converter/releases/tag/17.3.1.

**Comment by AwesomeGamer89** [comment]
Thanks
