### ISSUE TITLE
Keppy's MIDI Converter ignores audio frequency when rendering

### ISSUE THREAD

**Issue by Melvinkooi** [KaleidonKep99/Keppys-MIDI-Converter#34]
When you set a different audio frequency than the standard one (For example: 22.05kHz instead of the standard 44.1kHz) and you render your MIDI files to any file, it renders the MIDI in 44.1kHz instead of 22.05kHz.

I got this problem on version 17.3.1 on both portable and installed on x64. X86 also has this problem as well.

**Comment by KaleidonKep99** [comment]
I'll fix it now.

**Comment by KaleidonKep99** [comment]
Fixed.
https://github.com/KaleidonKep99/Keppys-MIDI-Converter/releases/tag/17.3.2

**Comment by Melvinkooi** [comment]
When i'm exporting a MIDI file in 22.05kHz it hangs at "The application is allocating memory for the conversion process, Please Wait...". Aborting the conversion doesn't work but you still can close the program itself. This also occurs on the standard audio frequency (44.1kHz).
Also, when using the preview option, it doesn't play the MIDI and very quickly goes back to "Waiting for commands.". This is both on x64 and x86 on 17.3.2.

**Comment by KaleidonKep99** [comment]
Oops, my bad! Fixed.
https://github.com/KaleidonKep99/Keppys-MIDI-Converter/releases/tag/17.3.3

**Comment by Melvinkooi** [comment]
I've just tested it and it works! The rendering to a different audio frequency works as intended on WAV, OGG and MP3. Thanks for the quick fix!
