### ISSUE TITLE
Crashes while Loading "Bad Apple!! feat. nomico Super-synthesized version V.2.mid"

### ISSUE THREAD

**Issue by KnockPlayz** [KaleidonKep99/Keppys-MIDI-Converter#35]
The midi is 245 million notes
![image](https://user-images.githubusercontent.com/22779352/36949036-18f9d378-1fb1-11e8-8bd2-6fed3f7ba420.png)

and my Pagefile is 80gb and I have 8gb DDR4 2166MHz RAM
![image](https://user-images.githubusercontent.com/22779352/36949002-ac3a834a-1fb0-11e8-939d-3a9a23074962.png)
Soundfonts
![image](https://user-images.githubusercontent.com/22779352/36949018-e0400f52-1fb0-11e8-8ce6-4807dd86a861.png)
****
And this is the error I get when rendering as a Ogg (LoudMax enabled + realtime) [On regular it doesn't give a error, it's only on realtime simulation]
![image](https://user-images.githubusercontent.com/22779352/36949030-034a8d60-1fb1-11e8-9e01-078ea9264b2b.png)
"==== Start of Keppy's MIDI Converter Error ====
MIDILoadError: Can not load this MIDI.

Are you sure you're not trying to open it in the 32-bit version of Keppy's MIDI Converter?
Also, try increasing the size of your paging file, you might not have enough RAM.
The MIDI might also be corrupted.

Additional info:
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at KeppyMIDIConverter.BASSControl.BASSStreamSystemRT(String str, Boolean PreviewMode)
   at KeppyMIDIConverter.BASSControl.BASSStreamSystemRT(String str, Boolean PreviewMode)
====  End of Keppy's MIDI Converter Error  ====
"

**Comment by linuxgemini** [comment]
The exception shows the culprit as "Exceeded all the memory".
Can you try raising the pagefile limit?

**Comment by KnockPlayz** [comment]
Alright

**Comment by KnockPlayz** [comment]
I put it up to 90, since I have 30 gb left on both my hdds
![image](https://user-images.githubusercontent.com/22779352/36949096-c037ea9e-1fb1-11e8-912c-0131c3814e12.png)
Let's see if it will have the same issue

**Comment by KnockPlayz** [comment]
Hmm, this is weird. It's only using 8gb of my pagefile when rendering then it gives the same error.

**Comment by KnockPlayz** [comment]
![image](https://user-images.githubusercontent.com/22779352/36949140-4c74c1b2-1fb2-11e8-9482-a011f32a51bd.png)
This is right before the error pops up

**Comment by KaleidonKep99** [comment]
Fixed as of version 18.0.2.
