### ISSUE TITLE
Add "Check for Updates"

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/Keppys-MIDI-Converter#5]
It is pretty lame going to the [releases page](http://github.com/KaleidonKep99/Keppys-MIDI-Converter/releases) and downloading the latest version, but it would be nice if we had a "Check for Updates" feature and download the latest version without going to the releases page, also "Auto-check for new version on startup".

**Comment by KaleidonKep99** [comment]
The update checker is already inside "Help" > "Information about the program".
About the auto-check for updates, well... I prefer to not annoy people with updates, because I update the code a lot.
