### ISSUE TITLE
Keppy's MIDI Converter randomly crashes while converting on 32-bit Windows

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/Keppys-MIDI-Converter#8]
While trying to convert all my songs to OGG/WAV on Windows 10 32-bit, I sometimes get a Windows error rather than a .NET error.

**Comment by KaleidonKep99** [comment]
What type of error, and what MIDI are you trying to convert? (+ With which soundfont?)

**Comment by DevanWolf** [comment]
Any MIDI and soundfont, but I meant like this:
![converterbug](https://cloud.githubusercontent.com/assets/8494722/16030551/ac46208a-31b7-11e6-817d-6557a7884aee.png)

**Comment by DevanWolf** [comment]
How come you never reply to me? Is BASS.NET updated?

**Comment by KaleidonKep99** [comment]
Yea, to the latest version.
Also, I'm never replying to you because I'm busy with real-life stuff...

Anyway, I tried to reproduce the problem, but nope, it never crashed for me.

**Comment by DevanWolf** [comment]
This just happened when I convert a lot (over 100) of MIDIs.

**Comment by KaleidonKep99** [comment]
I convrter 200-ish MIDIs and it still didn't crash for me.

**Comment by DevanWolf** [comment]
Here is my system specs that cause it:
Computer: Dell Vostro 1015
OS: Windows 10 32-Bit
RAM: 4GB
Processor: Intel(R) Core(TM)2 Duo CPU | T6670 @ 2.20GHz

**Comment by KaleidonKep99** [comment]
It's probably a limitation of Windows 10 32-bit, since I don't get this problem with Windows 10 64-bit.

**Comment by DevanWolf** [comment]
Oh... That's what happened on Windows 10 32-bit. I bet you can really fix this with this release note: "Fixed a random crash while converting on Windows 10 32-bit"

**Comment by DevanWolf** [comment]
Why didn't you answer me 2 weeks ago!? Like I said this only happens on 32 bit version.

**Comment by KaleidonKep99** [comment]
I can not fix this by releasing an update and adding "Fixed a random crash while converting on Windows 10 32-bit" to the changelog... Be patient.

Also, I tried to reproduce the problem on Windows 10 32-bit... And it worked just fine.
